- hosts: loadbalancers
  become: true
  tasks:
    - name: Install apache
      apt:
        name:
          - apache2
          - apache2-doc
        state: present
    - name: Ensure apache starts
      service: name=apache2 state=started enabled=yes

- hosts: webservers
  become: true
  tasks:
    - name: Install apache and php
      apt:
        name:
          - apache2
          - php
        state: present
